spring.application.name=oneteam-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/nombre_tu_db
spring.datasource.username=tu_usuario
spring.datasource.password=tu_password
spring.jpa.hibernate.ddl-auto=update